export const ELAN_PRODUCTS = [
  {
    id: 1,
    name: "Rose Hydrating Serum",
    category: "Skincare",
    price: "Ksh 2,500",
    description: "Deep hydration with rose extracts for glowing skin",
    src: "/elan-spa/products/rose-serum.jpg", // or use a placeholder
    features: ["Anti-aging", "Hydration", "Brightening"],
  },
  {
    id: 2,
    name: "Spa Luxury Lotion",
    category: "Bodycare",
    price: "Ksh 3,000",
    description: "Nourishing body moisturizer with shea butter",
    src: "/elan-spa/products/luxury-lotion.jpg",
    features: ["24hr Moisture", "Non-greasy", "Suitable for all skin types"],
  },
  {
    id: 3,
    name: "Essential Massage Oil",
    category: "Massage",
    price: "Ksh 4,500",
    description: "Aromatherapy blend for deep relaxation and muscle relief",
    src: "/elan-spa/products/massage-oil.jpg",
    features: ["Lavender & Chamomile", "Muscle Relaxation", "Stress Relief"],
  },
  {
    id: 4,
    name: "Coffee Body Scrub",
    category: "Exfoliation",
    price: "Ksh 2,800",
    description: "Exfoliating scrub with organic coffee grounds",
    src: "/elan-spa/products/coffee-scrub.jpg",
    features: ["Cellulite Reduction", "Exfoliation", "Natural Ingredients"],
  },
  {
    id: 5,
    name: "Waxing Kit Pro",
    category: "Waxing",
    price: "Ksh 6,000",
    description: "Professional home waxing kit with all essentials",
    src: "/elan-spa/products/waxing-kit.jpg",
    features: ["Complete Kit", "Easy Application", "Smooth Results"],
  },
  {
    id: 6,
    name: "Elan Spa Gift Set",
    category: "Packages",
    price: "Ksh 12,000",
    description: "Complete spa experience package - perfect for gifting",
    src: "/elan-spa/products/gift-set.jpg",
    features: ["5 Products", "Luxury Packaging", "Best Value"],
  },
  {
    id: 7,
    name: "Charcoal Facial Cleanser",
    category: "Skincare",
    price: "Ksh 2,200",
    description: "Deep pore cleansing with activated charcoal",
    src: "/elan-spa/products/charcoal-cleanser.jpg",
    features: ["Detoxifying", "Oil Control", "Gentle Formula"],
  },
  {
    id: 8,
    name: "Aromatherapy Candle Set",
    category: "Relaxation",
    price: "Ksh 3,500",
    description: "Set of 3 scented candles for ambient relaxation",
    src: "/elan-spa/products/candle-set.jpg",
    features: ["Soy Wax", "Long Burn", "3 Scents"],
  },
];
